/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "tertiary": "#240800",
        "on-secondary-fixed-variant": "#673c29",
        "on-secondary": "#ffffff",
        "primary": "#160f0e",
        "on-background": "#1e1b13",
        "secondary-fixed": "#ffdbcd",
        "surface-tint": "#675c59",
        "on-surface": "#1e1b13",
        "tertiary-fixed-dim": "#f5b9a0",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "inverse-primary": "#d2c3c0",
        "surface-container": "#f5eddf",
        "on-tertiary-container": "#b5816a",
        "surface-bright": "#fff8f0",
        "on-primary-container": "#968a87",
        "on-secondary-fixed": "#321204",
        "secondary-container": "#ffc1a7",
        "on-tertiary-fixed": "#321204",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "outline-variant": "#d1c4c0",
        "surface-dim": "#e1d9cb",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#663c29",
        "surface-container-high": "#efe7d9",
        "surface-container-highest": "#eae2d4",
        "on-primary-fixed-variant": "#4e4542",
        "surface-variant": "#eae2d4",
        "tertiary-container": "#3f1c0c",
        "surface": "#fff8f0",
        "on-primary-fixed": "#211a18",
        "background": "#fff8f0",
        "primary-container": "#2c2422",
        "secondary-fixed-dim": "#f6b99f",
        "on-surface-variant": "#4e4542",
        "surface-container-low": "#fbf3e4",
        "secondary": "#82533e",
        "outline": "#807572",
        "inverse-surface": "#343027",
        "primary-fixed-dim": "#d2c3c0",
        "primary-fixed": "#eedfdc",
        "tertiary-fixed": "#ffdbcd",
        "on-secondary-container": "#7a4d38",
        "inverse-on-surface": "#f8f0e2"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "space-md": "1rem",
        "margin-tablet": "2rem",
        "margin": "1rem",
        "space-sm": "0.5rem",
        "space-lg": "1.5rem",
        "gutter-desktop": "1.75rem",
        "margin-desktop": "3rem",
        "space-xl": "2.5rem",
        "space-xs": "0.25rem",
        "gutter": "1.25rem"
      },
      fontFamily: {
        "headline-xl-mobile": ["Epilogue", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Epilogue", "sans-serif"],
        "headline-xl": ["Epilogue", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Epilogue", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Epilogue", "sans-serif"],
        "headline-lg-mobile": ["Epilogue", "sans-serif"]
      },
      fontSize: {
        "headline-xl-mobile": ["30px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "26px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "30px", letterSpacing: "0em", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "0em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
